export ZDOTDIR="$HOME/.config/zsh"
export PATH="$PATH:$HOME/.local/homebrew/bin:$HOME/.local/homebrew/sbin"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
